/**
 * Onshape Oracle Client
 *
 * Pushes FeatureScript source to an Onshape Feature Studio, triggers
 * compilation, and reads back diagnostics via multiple strategies.
 *
 * Key finding: The Onshape public REST API does NOT expose Feature Studio
 * compilation notices (import warnings, syntax errors, etc.) through any
 * endpoint. Those diagnostics are generated by an internal compilation
 * service that only the browser-based Feature Studio editor can access.
 *
 * What we CAN get through the API:
 * 1. Runtime/regeneration errors — by adding a feature to a Part Studio
 *    and reading back its featureStatus + notices
 * 2. Expression evaluation errors — via evalFeatureScript
 * 3. Import resolution — by checking if the Feature Studio's source
 *    was accepted (no 4xx) and the microversion changed
 *
 * The validation loop:
 * 1. updateFeatureStudioContents → push source code
 * 2. GET partstudio/features     → read feature states + notices
 * 3. (optional) evalFeatureScript → test expressions
 */

import { loadConfig, validateConfig } from './config.js';

/**
 * @typedef {Object} OracleDiagnostic
 * @property {number} line      - 1-indexed line number (0 if unknown)
 * @property {number} column    - 1-indexed column (0 if unknown)
 * @property {'error'|'warning'|'info'} severity
 * @property {string} message   - Human-readable diagnostic text
 * @property {string} source    - 'compilation' | 'runtime' | 'notice' | 'import'
 */

/**
 * @typedef {Object} OracleResult
 * @property {boolean} success          - Whether the push + read cycle completed
 * @property {OracleDiagnostic[]} diagnostics
 * @property {number} durationMs        - Round-trip time
 * @property {string} [error]           - Transport-level error if success=false
 * @property {object} [raw]             - Raw API responses for debugging
 */

export class OnshapeOracle {
  /** @type {import('./config.js').OracleConfig} */
  #config;

  /**
   * @param {Partial<import('./config.js').OracleConfig>} [overrides]
   */
  constructor(overrides = {}) {
    const base = loadConfig();
    this.#config = { ...base, ...overrides };

    const { valid, missing } = validateConfig(this.#config);
    if (!valid) {
      throw new Error(
        `Oracle config incomplete — missing: ${missing.join(', ')}.\n` +
        `Set via env vars or .oraclerc.json. See .oraclerc.json.example.`
      );
    }
  }

  /**
   * Push FeatureScript source to Onshape and read back diagnostics.
   *
   * Strategy:
   * 1. Push code to Feature Studio (detects gross push failures)
   * 2. Read Part Studio features + featureStates (detects runtime errors)
   * 3. Try to extract feature names from source and check their states
   *
   * @param {string} source - Raw FeatureScript source code
   * @param {{ waitMs?: number, debug?: boolean }} [options]
   * @returns {Promise<OracleResult>}
   */
  async validate(source, { waitMs = 2000, debug = false } = {}) {
    const start = Date.now();
    const raw = {};

    try {
      // Step 1: Push code to Feature Studio
      const pushResponse = await this.#updateFeatureStudio(source);
      raw.push = { status: pushResponse.status, ok: pushResponse.ok };

      if (!pushResponse.ok) {
        const errorBody = await pushResponse.text();
        raw.pushError = errorBody;
        return {
          success: false,
          diagnostics: [{
            line: 0, column: 0, severity: 'error',
            message: `Feature Studio rejected code: ${pushResponse.status} — ${errorBody.slice(0, 200)}`,
            source: 'compilation',
          }],
          durationMs: Date.now() - start,
          error: `Push failed: ${pushResponse.status}`,
          ...(debug && { raw }),
        };
      }

      const pushData = await pushResponse.json();
      raw.pushData = { btType: pushData.btType, libraryVersion: pushData.libraryVersion };

      // Step 2: Wait for compilation / regeneration
      await sleep(waitMs);

      // Step 3: Read Part Studio features — this is where runtime notices live
      /** @type {OracleDiagnostic[]} */
      const diagnostics = [];
      let features = { features: [], featureStates: {}, imports: [] };

      if (this.#config.partStudioId) {
        features = await this.#getPartStudioFeatures();
        raw.features = {
          featureCount: features.features?.length ?? 0,
          stateKeys: Object.keys(features.featureStates ?? {}),
          imports: features.imports,
        };

        // Check feature states for errors
        const states = features.featureStates ?? {};
        for (const [featureId, state] of Object.entries(states)) {
          if (state.featureStatus && state.featureStatus !== 'OK') {
            diagnostics.push({
              line: 0, column: 0,
              severity: state.featureStatus === 'ERROR' ? 'error' : 'warning',
              message: `Feature "${featureId}": ${state.featureStatus}`,
              source: 'runtime',
            });
          }

          // Parse notices from feature state
          for (const notice of asArray(state.notices ?? state.errors ?? [])) {
            diagnostics.push(this.#normalizeNotice(notice, 'runtime'));
          }
        }

        // Check individual features for notices
        for (const feature of asArray(features.features)) {
          for (const notice of asArray(feature.notices ?? feature.errors ?? [])) {
            diagnostics.push(this.#normalizeNotice(notice, 'runtime'));
          }

          // Check feature's own featureStatus
          if (feature.featureStatus && feature.featureStatus !== 'OK') {
            diagnostics.push({
              line: 0, column: 0,
              severity: 'error',
              message: `Feature "${feature.name ?? feature.featureId}": ${feature.featureStatus}`,
              source: 'runtime',
            });
          }
        }

        // Check imports for resolution failures
        for (const imp of asArray(features.imports)) {
          if (imp.importStatus && imp.importStatus !== 'OK') {
            diagnostics.push({
              line: 0, column: 0,
              severity: 'warning',
              message: `Import failed: ${imp.path ?? imp.namespace ?? JSON.stringify(imp)}`,
              source: 'import',
            });
          }
        }
      }

      // Step 4: Try to detect known patterns in the source that would
      // cause Onshape errors (heuristic layer)
      diagnostics.push(...this.#heuristicChecks(source, pushData, features));

      return {
        success: true,
        diagnostics,
        durationMs: Date.now() - start,
        ...(debug && { raw }),
      };
    } catch (error) {
      return {
        success: false,
        diagnostics: [],
        durationMs: Date.now() - start,
        error: error.message,
        ...(debug && { raw }),
      };
    }
  }

  /**
   * Evaluate a FeatureScript lambda expression in a Part Studio context.
   *
   * @param {string} script - Lambda expression string
   * @returns {Promise<{ result: unknown, error?: string }>}
   */
  async evalScript(script) {
    const url = this.#url(
      `/api/v6/partstudios/d/${this.#config.documentId}/w/${this.#config.workspaceId}/e/${this.#config.partStudioId}/featurescript`
    );

    const response = await this.#fetch(url, {
      method: 'POST',
      body: JSON.stringify({ script }),
    });

    const data = await response.json();

    if (!response.ok) {
      return { result: null, error: `${response.status}: ${JSON.stringify(data)}` };
    }

    return { result: data };
  }

  // ── Private API methods ──

  /**
   * Push source code to the Feature Studio.
   * @param {string} contents
   */
  async #updateFeatureStudio(contents) {
    const { documentId, workspaceId, featureStudioId } = this.#config;
    const url = this.#url(
      `/api/v6/featurestudios/d/${documentId}/w/${workspaceId}/e/${featureStudioId}`
    );

    return this.#fetch(url, {
      method: 'POST',
      body: JSON.stringify({ contents }),
    });
  }

  /**
   * Get all features + featureStates from the Part Studio.
   * This is where runtime errors / regeneration notices appear.
   */
  async #getPartStudioFeatures() {
    const { documentId, workspaceId, partStudioId } = this.#config;
    const url = this.#url(
      `/api/v6/partstudios/d/${documentId}/w/${workspaceId}/e/${partStudioId}/features`
    );

    const response = await this.#fetch(url, { method: 'GET' });
    if (!response.ok) {
      return { features: [], featureStates: {} };
    }
    return response.json();
  }

  // ── Heuristic checks ──

  /**
   * Apply local heuristic checks that mirror known Onshape behaviors.
   * These cover cases where the API doesn't return explicit diagnostics
   * but we know from experience that Onshape would flag them.
   *
   * @param {string} source
   * @param {object} pushData - Response from updateFeatureStudioContents
   * @param {object} [partStudioData] - Response from getPartStudioFeatures
   * @returns {OracleDiagnostic[]}
   */
  #heuristicChecks(source, pushData, partStudioData) {
    /** @type {OracleDiagnostic[]} */
    const diagnostics = [];

    // Detect the current Onshape std lib version from Part Studio imports
    const currentStdVersion = this.#detectCurrentStdVersion(partStudioData);

    // Check: FeatureScript version header
    const versionMatch = source.match(/^FeatureScript\s+(\d+)\s*;/);
    if (!versionMatch) {
      diagnostics.push({
        line: 1, column: 0, severity: 'error',
        message: 'Missing FeatureScript version header',
        source: 'compilation',
      });
    }

    const declaredVersion = versionMatch ? parseInt(versionMatch[1]) : null;

    // Check: declared version vs actual Onshape version
    if (declaredVersion && currentStdVersion) {
      const currentMajor = parseInt(currentStdVersion.split('.')[0]);
      if (declaredVersion !== currentMajor) {
        diagnostics.push({
          line: 1, column: 0, severity: 'warning',
          message: `FeatureScript version ${declaredVersion} differs from Onshape's current std library version ${currentMajor}. ` +
            `Consider updating to: FeatureScript ${currentMajor};`,
          source: 'compilation',
        });
      }
    }

    // Check: import versions vs actual Onshape version
    const importRegex = /import\s*\(\s*path\s*:\s*"([^"]+)"\s*,\s*version\s*:\s*"([^"]+)"\s*\)/g;
    let importMatch;
    while ((importMatch = importRegex.exec(source)) !== null) {
      const [, path, version] = importMatch;
      const lineNum = source.slice(0, importMatch.index).split('\n').length;

      if (currentStdVersion && version !== currentStdVersion) {
        diagnostics.push({
          line: lineNum, column: 0, severity: 'warning',
          message: `Import "${path}" uses version "${version}" but Onshape's current std version is "${currentStdVersion}". ` +
            `Update to: import(path : "${path}", version : "${currentStdVersion}");`,
          source: 'compilation',
        });
      }

      // Also check consistency with the FS header
      const importMajor = version.split('.')[0];
      if (declaredVersion && parseInt(importMajor) !== declaredVersion) {
        diagnostics.push({
          line: lineNum, column: 0, severity: 'warning',
          message: `Import version "${version}" doesn't match FeatureScript header version ${declaredVersion}`,
          source: 'compilation',
        });
      }
    }

    return diagnostics;
  }

  /**
   * Extract the current Onshape std library version from Part Studio imports.
   * The Part Studio always has a default import that reveals the current version.
   *
   * @param {object} [partStudioData]
   * @returns {string|null} e.g. "2960.0"
   */
  #detectCurrentStdVersion(partStudioData) {
    const imports = partStudioData?.imports ?? [];
    for (const imp of asArray(imports)) {
      if (imp.path?.startsWith('onshape/std/') && imp.version) {
        return imp.version;
      }
    }
    return null;
  }

  // ── Helpers ──

  /**
   * Normalize a single Onshape notice object.
   *
   * @param {object} notice
   * @param {'compilation'|'runtime'|'notice'|'import'} source
   * @returns {OracleDiagnostic}
   */
  #normalizeNotice(notice, source) {
    const line = notice.startLineNumber ?? notice.line ?? notice.lineNumber ?? 0;
    const column = notice.startColumn ?? notice.column ?? 0;
    const message = notice.message ?? notice.text ?? notice.description ?? JSON.stringify(notice);

    let severity = 'error';
    const rawLevel = (notice.level ?? notice.severity ?? notice.type ?? '').toString().toLowerCase();
    if (rawLevel.includes('warn')) severity = 'warning';
    else if (rawLevel.includes('info') || rawLevel.includes('notice')) severity = 'info';

    return { line, column, severity, message, source };
  }

  /**
   * Build a full URL from a path.
   * @param {string} path
   * @returns {string}
   */
  #url(path) {
    return `${this.#config.baseUrl}${path}`;
  }

  /**
   * Authenticated fetch wrapper.
   * @param {string} url
   * @param {RequestInit} options
   * @returns {Promise<Response>}
   */
  async #fetch(url, options = {}) {
    const { accessKey, secretKey } = this.#config;
    const credentials = Buffer.from(`${accessKey}:${secretKey}`).toString('base64');

    return fetch(url, {
      ...options,
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json;charset=UTF-8',
        'Authorization': `Basic ${credentials}`,
        ...options.headers,
      },
    });
  }
}

/** @param {unknown} value @returns {unknown[]} */
function asArray(value) {
  if (Array.isArray(value)) return value;
  if (value == null) return [];
  return [value];
}

/** @param {number} ms */
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
